import pandas as pd
from pylab import *
import dfdf

# получение данных по ММВБ, Futsee100 за 01.10.2007-01.12.2015
micexurl = \
    'http://www.micex.ru/issrpc/marketdata/stock/index/history/' \
    'by_ticker/index_history_MICEXINDEXCF.csv?secid=MICEXINDEXCF&lang=ru'
url='http://real-chart.finance.yahoo.com/' \
    'table.csv?s=%5EFTSE&d=3&e=17&f=2016&g=d&a=0&b=3&c=1984&ignore=.csv'
micex = pd.read_csv(micexurl, sep=';', index_col=2, parse_dates = [2])
micex = micex[micex.index < datetime.datetime(2016, 1, 1)]
micex = micex[micex.index > datetime.datetime(2007, 10, 1)]
futsee=pd.read_csv(url, sep=',', index_col=0, parse_dates=[0])
futsee=futsee[futsee.index<datetime.datetime(2016, 1, 1)]
futsee=futsee[futsee.index>datetime.datetime(2007, 10, 1)]
# расчет max, min, mean, median значений индексов за квартал в рамках 2007-2015

def mmmm(oo,q,s,s1,t,t1,t2,t3,u,f1,f2,f3,c1,c2,c3):
    m=t2*(micex[t1].resample('Q', how=t)/t3)
    f=f2*(futsee[f1].resample('Q',how=t)/f3)
    c=c1*(oo(dfdf.dfdf(u'D:\work\data1\shanchai.xlsx',c2), 59)/c3)
    a=oo(dfdf.dfdf(u'D:\work\data1\dow&jones.xlsx',u), 62)
    k=s1*(oo(dfdf.dfdf(u'D:\work\data1\kazah.xlsx',q), 63)/s)
    ind_un=np.concatenate([
                           a.loc[706],
                           a.loc[768],
                           a.loc[832],
                           a.loc[898],
                           a.loc[962],
                           a.loc[1026],
                           a.loc[1090],
                           a.loc[1154],
                           a.loc[1218],
                           a.loc[1282],
                           a.loc[1346],
                           a.loc[1410],
                           a.loc[1474],
                           a.loc[1538],
                           a.loc[1602],
                           a.loc[1666],
                           a.loc[1730],
                           a.loc[1796],
                           a.loc[1862],
                           a.loc[1926],
                           a.loc[1990],
                           a.loc[2054],
                           a.loc[2118],
                           a.loc[2182],
                           a.loc[2246],
                           a.loc[2310],
                           a.loc[2374],
                           a.loc[2438],
                           a.loc[2502],
                           a.loc[2566],
                           a.loc[2630],
                           a.loc[2694],
                           a.loc[2758],
                            c.loc[60],
                            c.loc[120],
                            c.loc[180],
                            c.loc[240],
                            c.loc[300],
                            c.loc[360],
                            c.loc[420],
                            c.loc[480],
                            c.loc[540],
                            c.loc[600],
                            c.loc[660],
                            c.loc[720],
                            c.loc[780],
                            c.loc[840],
                            c.loc[900],
                           c.loc[960],
                           c.loc[1020],
                           c.loc[1080],
                           c.loc[1140],
                           c.loc[1200],
                           c.loc[1260],
                            c.loc[1320],
                            c.loc[1380],
                            c.loc[1440],
                            c.loc[1500],
                            c.loc[1560],
                            c.loc[1620],
                            c.loc[1680],
                            c.loc[1740],
                            c.loc[1800],
                            c.loc[1860],
                            c.loc[1920],
                            c.loc[1971],
                            f,
                           m,
                           k.loc[65],
                            k.loc[130],
                            k.loc[195],
                            k.loc[260],
                            k.loc[325],
                            k.loc[390],
                            k.loc[455],
                            k.loc[520],
                            k.loc[585],
                            k.loc[650],
                            k.loc[715],
                            k.loc[780],
                            k.loc[845],
                            k.loc[910],
                            k.loc[975],
                            k.loc[1040],
                            k.loc[1105],
                            k.loc[1170],
                            k.loc[1235],
                            k.loc[1300],
                            k.loc[1365],
                            k.loc[1430],
                            k.loc[1495],
                            k.loc[1560],
                            k.loc[1625],
                            k.loc[1690],
                           k.loc[1755],
                           k.loc[1820],
                           k.loc[1885],
                           k.loc[1950],
                           k.loc[2005],
                           k.loc[2030],
                           k.loc[2036]])

    return ind_un

# Данные по рынкам РЕПО стран
url = 'http://www.micex.ru/issrpc/marketdata/stock/index/history/' \
      'by_ticker/index_history_MICEXBORRON.csv?secid=MICEXBORRON&lang=ru'
micex_r = pd.read_csv(url, sep=';', index_col=2, parse_dates = [2])
micex_r = micex_r[micex_r.index < datetime.datetime(2016, 1, 1)]
micex_r = micex_r[micex_r.index > datetime.datetime(2007, 10, 1)]
def repo(oo,u,c2,f2,q,t,t1,):

    usa_min=oo(dfdf.dfdf(u'D:\work\data1\ouss.xlsx',u), 60)
    c_min=oo(dfdf.dfdf(u'D:\work\data1\shibor.xlsx',c2), 60)
    usa_mean=oo(dfdf.dfdf(u'D:\work\data1\eng.xlsx',f2), 62)
    kaz_min=oo(dfdf.dfdf(u'D:\work\data1\TONIA.xlsx',q), 59)
    m=micex_r[t1].resample('Q', how=t)





    repo=np.concatenate([   usa_min.loc[744],
                            usa_min.loc[806],
                            usa_min.loc[868],
                            usa_min.loc[930],
                            usa_min.loc[992],
                            usa_min.loc[1054],
                            usa_min.loc[1116],
                            usa_min.loc[1178],
                            usa_min.loc[1240],
                            usa_min.loc[1302],
                            usa_min.loc[1364],
                            usa_min.loc[1426],
                            usa_min.loc[1488],
                            usa_min.loc[1550],
                            usa_min.loc[1612],
                           usa_min.loc[1674],
                           usa_min.loc[1736],
                           usa_min.loc[1798],
                           usa_min.loc[1860],
                           usa_min.loc[1922],
                           usa_min.loc[1984],
                            usa_min.loc[2046],
                            usa_min.loc[2108],
                            usa_min.loc[2170],
                            usa_min.loc[2232],
                            usa_min.loc[2294],
                            usa_min.loc[2356],
                            usa_min.loc[2418],
                            usa_min.loc[2480],
                            usa_min.loc[2542],
                            usa_min.loc[2604],
                            usa_min.loc[2666],
                            usa_min.loc[2728],
                            c_min.loc[62],
                            c_min.loc[124],
                            c_min.loc[186],
                            c_min.loc[248],
                            c_min.loc[310],
                            c_min.loc[372],
                            c_min.loc[434],
                            c_min.loc[496],
                            c_min.loc[558],
                            c_min.loc[620],
                            c_min.loc[682],
                            c_min.loc[744],
                            c_min.loc[806],
                            c_min.loc[870],
                            c_min.loc[932],
                            c_min.loc[994],
                            c_min.loc[1056],
                            c_min.loc[1118],
                            c_min.loc[1180],
                            c_min.loc[1242],
                            c_min.loc[1304],
                            c_min.loc[1366],
                            c_min.loc[1428],
                            c_min.loc[1490],
                            c_min.loc[1552],
                            c_min.loc[1614],
                           c_min.loc[1676],
                           c_min.loc[1740],
                           c_min.loc[1804],
                           c_min.loc[1866],
                           c_min.loc[1928],
                           c_min.loc[1990],
                            c_min.loc[2052],
                            usa_mean.loc[64],
                            usa_mean.loc[128],
                            usa_mean.loc[192],
                            usa_mean.loc[256],
                            usa_mean.loc[320],
                            usa_mean.loc[384],
                            usa_mean.loc[448],
                            usa_mean.loc[512],
                            usa_mean.loc[576],
                            usa_mean.loc[640],
                            usa_mean.loc[704],
                            usa_mean.loc[768],
                            usa_mean.loc[832],
                            usa_mean.loc[898],
                            usa_mean.loc[962],
                            usa_mean.loc[1026],
                            usa_mean.loc[1090],
                            usa_mean.loc[1154],
                            usa_mean.loc[1218],
                            usa_mean.loc[1282],
                            usa_mean.loc[1346],
                            usa_mean.loc[1410],
                            usa_mean.loc[1474],
                            usa_mean.loc[1538],
                            usa_mean.loc[1602],
                            usa_mean.loc[1666],
                           usa_mean.loc[1730],
                           usa_mean.loc[1796],
                           usa_mean.loc[1862],
                           usa_mean.loc[1926],
                           usa_mean.loc[1990],
                           usa_mean.loc[2054],
                            usa_mean.loc[2084],
                            m,kaz_min.loc[61],
                            kaz_min.loc[122],
                            kaz_min.loc[183],
                            kaz_min.loc[244],
                            kaz_min.loc[305],
                            kaz_min.loc[366],
                            kaz_min.loc[427],
                            kaz_min.loc[488],
                            kaz_min.loc[549],
                            kaz_min.loc[610],
                            kaz_min.loc[671],
                            kaz_min.loc[732],
                            kaz_min.loc[793],
                            kaz_min.loc[854],
                            kaz_min.loc[915],
                            kaz_min.loc[976],
                            kaz_min.loc[1037],
                            kaz_min.loc[1098],
                            kaz_min.loc[1160],
                            kaz_min.loc[1221],
                            kaz_min.loc[1282],
                            kaz_min.loc[1343],
                            kaz_min.loc[1404],
                            kaz_min.loc[1465],
                            kaz_min.loc[1526],
                            kaz_min.loc[1587],
                           kaz_min.loc[1648],
                           kaz_min.loc[1719],
                           kaz_min.loc[1780],
                           kaz_min.loc[1841],
                           kaz_min.loc[1902],
                           kaz_min.loc[1963],
                           kaz_min.loc[2026]
                            ])
    return repo




